language: objective-c
python:
    - "2.7"

env:
    global:
        - PACKAGE="EvalPrinter"
    matrix:
        - SUBLIME_TEXT_VERSION="2"
        - SUBLIME_TEXT_VERSION="3"

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh

install:
    - sh travis.sh bootstrap

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install -g coffee-script
script:
    - sh travis.sh run_tests
